### ISSUE TITLE
OneHotEncoder Failure: Simple example failure

### ISSUE THREAD

**Issue by chclam** [openml-labs/gama#147]
An error occurs when I'm trying to run the following simple example from the main page:

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss, accuracy_score
from gama import GamaClassifier

if __name__ == '__main__':
    X, y = load_breast_cancer(return_X_y=True)
    X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=0)

    automl = GamaClassifier(max_total_time=180, store="nothing")
    print("Starting `fit` which will take roughly 3 minutes.")
    automl.fit(X_train, y_train)

    label_predictions = automl.predict(X_test)
    probability_predictions = automl.predict_proba(X_test)

    print('accuracy:', accuracy_score(y_test, label_predictions))
    print('log loss:', log_loss(y_test, probability_predictions))
    # the `score` function outputs the score on the metric optimized towards (by default, `log_loss`)
    print('log_loss', automl.score(X_test, y_test))
```
The error that I get:

```
Traceback (most recent call last):
  File "/Users/chris/Development/gradproject/issues/gama/gama/./test.py", line 13, in <module>
    automl.fit(X_train, y_train)
  File "/Users/chris/Development/gradproject/issues/gama/gama/gama/GamaClassifier.py", line 134, in fit
    super().fit(x, y, *args, **kwargs)
  File "/Users/chris/Development/gradproject/issues/gama/gama/gama/gama.py", line 502, in fit
    self._x, self._basic_encoding_pipeline = basic_encoding(
  File "/Users/chris/Development/gradproject/issues/gama/gama/gama/utilities/preprocessing.py", line 63, in basic_encoding
    x_enc = encoding_pipeline.fit_transform(x, y=None)  # Is this dangerous?
  File "/usr/local/lib/python3.9/site-packages/sklearn/pipeline.py", line 434, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.9/site-packages/sklearn/base.py", line 847, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.9/site-packages/category_encoders/one_hot.py", line 152, in fit
    oe_missing_strat = {
KeyError: 'ignore'
```

It seems to be caused by assigning an invalid keyword to the `handle_missing` function parameter to `OneHotEncoder` in the dependency `category_encoders`.
According to the [docs](https://contrib.scikit-learn.org/category_encoders/onehot.html), the valid keywords are as follows: `error`, `return_nan`, `value`, and `indicator`, where `value` is the default.

**Comment by PGijsbers** [comment]
Hi, thanks for opening the issue and providing a solution 👍
It looks like this is specific to the latest release (and was undocumented and without deprecation warnings) :)

For those that run into this issue until a new gama PyPI release is available: please downgrade category encoders to 2.3:
` pip install category-encoders==2.3`

**Comment by chclam** [comment]
Hey, I'm glad to be of any help 👍

**Comment by alanwilter** [comment]
Never mind, changed in `resources/config.yaml` to `python: 3.8` and it worked.

**Comment by PGijsbers** [comment]
As expected: the latest GAMA release (22.0.0) is only available for Py 3.8+
