### ISSUE TITLE
Issue with Pickling Local Object in Custom Gama Classifier Implementation

### ISSUE THREAD

**Issue by simonprovost** [openml-labs/gama#199]
Hello @PGijsbers,

I hope you are doing well :) I am reaching out in regards to the issue we previously discussed about developing a new AutoML system around GAMA as an outer wrapper ([Issue #191](#191)).

I am excited to share that I've made substantial progress with my implementation. Specifically, I have been able to successfully design the creation of individuals in a sequential step manner, as we had discussed earlier. Moreover, I've managed to implement the population creation, and individual pipeline fitting using our custom pipeline (i.e, we create a population, took randomly one of the individual, called its fit function which basically process the pipeline of the individual).

However, I have run into an obstacle while attempting to call the `fit` function of our custom Gama classifier. Despite the fact that I have solved a few related issues along the road, I am currently unable to identify an error we encountered. The error appears to be related to preserving a local object, but I have no idea how to proceed / where to dig down. I believe this has something to do with Threading operations, but what can I do? The errors encountered:

```shell
 File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'EvaluationLibrary.__init__.<locals>.main_node_str'
```

For my current implementation, I'm using the Random Search base search estimator. My goal is to have an end-to-end process working before moving onto building a Bayesian optimisation search algorithm. During the Random Search process, I'm able to print the following:

```python
# [...]/gama/search_methods/random_search.py
[...]
    with AsyncEvaluator() as async_:
        for individual in start_candidates:
            print("Evaluating start candidates")
            print(f"Individual: {individual}")
            print(f"operations.evaluate.func's name: {operations.evaluate.func.__name__}")
            async_.submit(operations.evaluate, individual) # Following that line I am lost where to look at (see next)
[...]
```

This results in outputs like the following:

```
> Evaluating start candidates

> Individual: Individual a471a748-8f09-4788-a7e6-104f1c1f93fb
Pipeline: ExtraTreesClassifier(DummyStep(data, DummyStep.dummy_parameter="some_value"), ExtraTreesClassifier.bootstrap=True, ExtraTreesClassifier.criterion='gini', ExtraTreesClassifier.max_features=0.6000000000000001, min_samples_leaf=17, min_samples_split=3, ExtraTreesClassifier.n_estimators=500)
Fitness: None

> operations.evaluate.func's name: evaluate_individual
```

However, after this, the aforementioned issue arises. Despite embedding print statements within the `evaluate_individual` (`gama/genetic_programming/compilers/scikitlearn.py`) method, none of the print statements even before any procedures been executed within the function are printed to the console, and here is the strange behaviour. While I am unable to uncover the root cause of this issue. I am currently seeking guidance on how to proceed if you have any single suggestion please :)

For your reference, I am using a forked version of Gama, integrated locally into my project using poetry. The build process is functioning as expected and I am executing this on a MacBook Pro M2 Ventura, stable version.

Any insights or suggestions you could provide would be deeply appreciated 👌 Thank you very much for your time and assistance! Have a lovely evening,
Best wishes,

**Comment by simonprovost** [comment]
**EDIT 1 (06 th June - 6:30 p.m):** I have tried various search algorithms to ensure that the issue is not on the Random Search side. AsyncEA and ASHA both experience issues with the pickle object. Not identical object, but identical attribute error: "Can not pickle local object [X]" X being the object.

```Some Examples
- AttributeError: Can't pickle local object 'AsyncEA.__init__.<locals>.get_parent'
- AttributeError: Can't pickle local object 'AsynchronousSuccessiveHalving.__init__.<locals>.<lambda>'
```

**Comment by simonprovost** [comment]
**EDIT 2 (06 th June - 10:30 p.m):**  I have finally came around the idea that threading does not easily serialise local / self methods. Thus, all methods concerned by this pickle serialise/load issue _(actually two `main_node_str` and `get_pipeline_str` had to create a function for the pipeline lambda in the self.fields dict instantiation, in `gama/utilities/evaluation_library.py` and `gama/logging/evaluation_logger.py`, respectively)_ been moved out of their respective classes as `static` methods and it seems to work out.

1. First and foremost, this surely is a quick patch; I am confident that it should function as-is without these changes; did I miss anything?
2. If it does work, may any of these two functions be a result of a run failing to finish properly? After the time out (i.e, I deliberately set the `max_total_time` to 300 seconds) it does not terminate the fitting process and complete the post-processing. I have to SIGINT (i.e, `ctrl + c`) the process once to start the post-processing method, and again to exit the procedure, which is inconvenient because I want to finish my `main.py` script with prediction on test set etc. Do you have any ideas? I will keep looking for it, and if it does not appear to be related to the existing issue, I will open a new one.

Cheers

**Comment by simonprovost** [comment]
EDIT 3 (07 th June - 12 a.m): While the patch of EDIT-2 appears to be heading toward making work an end-to-end process. The termination when the maximum eval time has been reached does not appear to work very well. I started by setting the maximum eval time to 600, and the eval of one individual is set to 60 by default (10% of max eval time). When that limit is exceeded, there is a difficulty with Pickle Load/Unload once more. What are your thoughts about that? Where should I look per your suggestion?

FYI: I am currently using FiSH shell. Which is POSIX based so should not have issues with Kill command to kill a PID.

```
Traceback (most recent call last):
  File "<project_path>/lib/python3.10/site-packages/gama/search_methods/random_search.py", line 69, in random_search
    future = operations.wait_next(async_)
  File "<project_path>/lib/python3.10/site-packages/gama/genetic_programming/operator_set.py", line 65, in wait_next
    future = async_evaluator.wait_next()
  File "<project_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 218, in wait_next
    self._control_memory_usage()
  File "<project_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 293, in _control_memory_usage
    self._stop_worker_process(proc)
  File "<project_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 252, in _stop_worker_process
    process.wait(timeout=60)
  File "<project_path>/lib/python3.10/site-packages/psutil/__init__.py", line 1270, in wait
    self._exitcode = self._proc.wait(timeout)
  File "<project_path>/lib/python3.10/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
  File "<project_path>/lib/python3.10/site-packages/psutil/_psosx.py", line 520, in wait
    return _psposix.wait_pid(self.pid, timeout, self._name)
  File "<project_path>/lib/python3.10/site-packages/psutil/_psposix.py", line 137, in wait_pid
    interval = sleep(interval)
  File "<project_path>/lib/python3.10/site-packages/psutil/_psposix.py", line 114, in sleep
    raise TimeoutExpired(timeout, pid=pid, name=proc_name)
psutil.TimeoutExpired: timeout after 60 seconds (pid=93745)

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "<project_path>/main.py", line 76, in <module>
    main()
  File "<project_path>/main.py", line 41, in main
    customGamaClassifier.fit(X_train, y_train)
  File "<project_path>/lib/python3.10/site-packages/gama/CustomGamaClassifier.py", line 244, in fit
    super().fit(x, y, *args, **kwargs)
  File "<project_path>/lib/python3.10/site-packages/gama/gama.py", line 609, in fit
    self._search_phase(warm_start, timeout=fit_time)
  File "<project_path>/lib/python3.10/site-packages/gama/gama.py", line 685, in _search_phase
    self._search_method.search(self._operator_set, start_candidates=pop)
  File "<project_path>/lib/python3.10/site-packages/gama/search_methods/random_search.py", line 28, in search
    random_search(operations, self.output, start_candidates)
  File "<project_path>/lib/python3.10/site-packages/gama/search_methods/random_search.py", line 60, in random_search
    with AsyncEvaluator() as async_:
  File "<project_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 151, in __exit__
    self.clear_queue(self._input)
  File "<project_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 169, in clear_queue
    q.get(timeout=0.001)
  File "<python_path>/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, '\xa3'.
```

**Comment by simonprovost** [comment]
**EDIT-4 (7th June, 11 p.m):** After multiple attempts, I was able to complete the entire fit procedure after the maximum evaluation time had expired. Nonetheless, what is surprising is that it has the same console log issues as _EDIT-3_, but still provides access to the post-processing procedure to conclude the entire fit process - EDIT-4. I do not know, perhaps it is a side effect or something else. If you know where I could conduct more digging, I would be extremely grateful:

```

INFO:gama.utilities.generic.async_evaluator:GAMA exceeded memory usage (0, 1).
INFO:gama.utilities.generic.async_evaluator:Terminating 81857 due to memory usage.
An error occurred in function fit: 
TimeoutException - pipeline evaluation timed out.
Pipeline evaluation interrupted by timeout exception- returnning the error in  cascade.
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, '\x00'.
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, '\x00'.

INFO:gama.genetic_programming.operations:Longitudinal random expression creation complete with DecisionTreeClassifier(DummyStep(data), DecisionTreeClassifier.max_depth=7, min_samples_leaf=1, min_samples_split=8)

ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, '\x00'.
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
_pickle.UnpicklingError: invalid load key, '\x00'.
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
ERROR:root:Stopping daemon due to exception
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<poetry_env_path>/lib/python3.10/site-packages/gama/utilities/generic/async_evaluator.py", line 381, in evaluator_daemon
    future = input_queue.get(block=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
EOFError: Ran out of input

DEBUG:gama.utilities.generic.async_evaluator:Signaling 1 subprocesses to stop.
INFO:gama.gama:Search phase evaluated 19 individuals.
INFO:gama.utilities.generic.timekeeper:STOP: search RandomSearch after 53.9941s.
INFO:gama.utilities.generic.timekeeper:START: postprocess BestFitPostProcessing
Type Final Estimator: <class 'sklearn.tree._classes.DecisionTreeClassifier'>
INFO:gama.gama:Best pipeline: <not displaying for the sake of breviti>
INFO:gama.utilities.generic.timekeeper:STOP: postprocess BestFitPostProcessing after 0.0549s.
```

**Comment by simonprovost** [comment]
**EDIT-5 (8th June, 12 a.m):** _The final edit of the day._ I discovered by chance that we can configure the maximum number of random search evaluations to do. While still investigating why the overall fit pipeline does not complete once the maximum eval time has been reached, I began a run with the maximum number of random search evaluations set to a low value in the hope that it would run more quickly and enable me to investigate more quickly. Nonetheless, using the max evaluations with a low number, i.e. to avoid the max eval time timeout, it appears to run an end to end pipeline; I can even invoke the predict proba of the Gama classifier to obtain the classification report, confusion matrix, etc. Which is very reassuring, I will not fib 🤥 However, I would love the process to work without using the max evaluations parameter; 

I just wanted to mention that in case it is necessary to comprehend my situation.

By max evaluations I refer to:
```python
def random_search(
    operations: OperatorSet,
    output: List[Individual],
    start_candidates: List[Individual],
    max_evaluations: Optional[int] = None,
) -> List[Individual]:
[...]
```

**Comment by PGijsbers** [comment]
> This feels like a quick patch; I am confident that it should function without these changes; did I miss anything? any thoughts?

To the best of my knowledge, this is how it has to be. Pickle tries to re-import all the functions/classes etc., and these local functions are not importable.

I am not sure where the `EOF` errors come from, but:

> `INFO:gama.gama:Best pipeline: <not displaying for the sake of brevity>`

Are your pipelines very long? The errors did not happen before you made changes, correct? Maybe it is possible to try and isolate changes bit by bit to see when the error gets introduced.

**Comment by simonprovost** [comment]
Re,

It appears that creating a (condo) new environment, installing GAMA with pip, and executing the example from the official readme are error-free. Therefore, the issues seems to be coming from any of my implementation but weird I got not lead on via the logs / nor any of my tonnes of print statements.

Will investigate further, but as quick thought, I believe that saving/loeading my custom estimators is probably the challenging part, although no console logs indicate this, but will look into that. If you have any insight into how the maximum evaluation time works/route, I would greatly appreciate it.

Cheers :)

**Comment by simonprovost** [comment]
@PGijsbers Heya. The issue does not appear to be directly related to GAMA. No need for you to respond further on the wire EOFERROR because I will explain myself about it within the day. However, I would appreciate an explanation for why these lambdas are not static in the main branch? Why did I need to move them out myself? Quite curious.

Cheers.

**Comment by simonprovost** [comment]
> I don't know _why_ I didn't merge it at the time though, perhaps I too found it a bit of a "hack" and wanted to investigate if there were other ways first.

100% understandable. However, based on my observations around some Github issues and Stack. Posts, this is Pickle's choice, and it is possible that this is one of your only option if you want to stay with Pickle. Nonetheless, allowing the function to stay within the class and decorating it with `@staticmethod` would at the very least make it more elegant, but does it work, I do not know, to try maybe. Yet, this does not exclude the issue with in-line lambda.

For in-line lambda, I still have seen this cloud pickling fork,  which I cite `cloudpickle supports pickling for lambda functions along with functions and classes defined interactively in the __main__ module.` - [CloudPickle](https://github.com/cloudpipe/cloudpickle). Could be worth investigating. However, for my design now it do works as-is (i.e, by moving out of the classes necessary functions/lambdas), so will continue like that for now.

In the interim, this issue will be resolved in the next comment I make for newcomers experiencing the same problems as I expressed initially.
